#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'
 cookbook 'apt'
 cookbook 'apache2'
 cookbook 'build-essential'
 cookbook 'openssl'
 cookbook 'php'
 cookbook 'git'
 cookbook 'selinux'
 cookbook 'sudo'
 cookbook 'vim'
 cookbook 'postfix'
 cookbook 'cron'
 cookbook 'database'
 cookbook 'mysql'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
