default['msic']['url'] = 'https://msic.com.au'
default['msic']['docroot'] = '/home/msic'
default['msic']['name'] = 'msic'
default['msic']['server_name'] = 'msic.local'
default['msic']['adminemail'] = 'mganesan@identiv.com'
default['msic']['server_aliases'] = [ "www.msic.local",  "msic.local", "msic.dev.local" ]
default['msic']['database']['name'] = 'msic'
default['msic']['database']['user'] = 'msicuser'
default['msic']['database']['password'] = 'msicpass'