default['fileserver']['url'] = 'http://local.fileserver'
default['fileserver']['docroot'] = '/home/fileserver'
default['fileserver']['name'] = 'fileserver'
default['fileserver']['server_name'] = 'fileserver.local'
default['fileserver']['adminemail'] = 'mganesan@identiv.com'
default['fileserver']['server_aliases'] = [ "www.fileserver.local",  "fileserver.local", "fileserver.dev.local" ]
default['fileserver']['database']['name'] = 'fileserver'
default['fileserver']['database']['user'] = 'fileserveruser'
default['fileserver']['database']['password'] = 'fileserverpass'